coding_task:
  description: >
    Write Python Code to achieve this assignment: {assignment}
  expected_output: >
    A text file that contains the code itself, along with the output of the code.
  agent: coder
  output_file: output/code_and_output.txt
